version: '3.8'

services:
  snap-scraper-api:
    build: .
    container_name: snap-scraper-api
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    command: >
      sh -c "uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    networks:
      - app_network
networks:
  app_network:
    driver: bridge
